/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardManageTweetRouteImport } from './routes/dashboard/manage-tweet'
import { Route as DashboardImportTweetRouteImport } from './routes/dashboard/import-tweet'
import { Route as DashboardCreateTweetRouteImport } from './routes/dashboard/create-tweet'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageTweetRoute = DashboardManageTweetRouteImport.update({
  id: '/manage-tweet',
  path: '/manage-tweet',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportTweetRoute = DashboardImportTweetRouteImport.update({
  id: '/import-tweet',
  path: '/import-tweet',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCreateTweetRoute = DashboardCreateTweetRouteImport.update({
  id: '/create-tweet',
  path: '/create-tweet',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard/create-tweet': typeof DashboardCreateTweetRoute
  '/dashboard/import-tweet': typeof DashboardImportTweetRoute
  '/dashboard/manage-tweet': typeof DashboardManageTweetRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/create-tweet': typeof DashboardCreateTweetRoute
  '/dashboard/import-tweet': typeof DashboardImportTweetRoute
  '/dashboard/manage-tweet': typeof DashboardManageTweetRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard/create-tweet': typeof DashboardCreateTweetRoute
  '/dashboard/import-tweet': typeof DashboardImportTweetRoute
  '/dashboard/manage-tweet': typeof DashboardManageTweetRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/create-tweet'
    | '/dashboard/import-tweet'
    | '/dashboard/manage-tweet'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard/create-tweet'
    | '/dashboard/import-tweet'
    | '/dashboard/manage-tweet'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/create-tweet'
    | '/dashboard/import-tweet'
    | '/dashboard/manage-tweet'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage-tweet': {
      id: '/dashboard/manage-tweet'
      path: '/manage-tweet'
      fullPath: '/dashboard/manage-tweet'
      preLoaderRoute: typeof DashboardManageTweetRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import-tweet': {
      id: '/dashboard/import-tweet'
      path: '/import-tweet'
      fullPath: '/dashboard/import-tweet'
      preLoaderRoute: typeof DashboardImportTweetRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/create-tweet': {
      id: '/dashboard/create-tweet'
      path: '/create-tweet'
      fullPath: '/dashboard/create-tweet'
      preLoaderRoute: typeof DashboardCreateTweetRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCreateTweetRoute: typeof DashboardCreateTweetRoute
  DashboardImportTweetRoute: typeof DashboardImportTweetRoute
  DashboardManageTweetRoute: typeof DashboardManageTweetRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCreateTweetRoute: DashboardCreateTweetRoute,
  DashboardImportTweetRoute: DashboardImportTweetRoute,
  DashboardManageTweetRoute: DashboardManageTweetRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
